website/autostats/urls.py
from django.contrib import admin
from django.urls import path, include
from . import descriptive_dash, descriptive_value_dash

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('dashboards.urls','django_plotly_dash.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

website/dashboards/urls.py
from django.urls import path
from . import views

app_name = 'dashboards'

urlpatterns = [
    path('', views.index, name='index'),
    path('make',views.make_choices_ajax,name='make_choices_ajax'),
    path('model',views.model_choices_ajax,name='model_choices_ajax'),
    path('year',views.year_choices_ajax,name='year_choices_ajax'),
    path('validate',views.validate_dashboard,name='validate_dashboard'),
    path('links',views.update_link_cookies,name='update_link_cookies'),
    path('remove_links',views.clear_cookies,name='clear_cookies'),
    path('dashboard/descriptive=<str:descriptive>/value=<str:value>/<str:type>/<str:make>/<str:model>/<str:year>/',views.dashboard_display,name='dashboard_display'),
]

website/dashboards/models.py
from django.db import models

# Create your models here.
class vehicle_image(models.Model):

    full_vehicle = models.CharField(max_length=100,primary_key=True)
    image_path = models.CharField(max_length=150,null=True)

    class Meta:
        db_table = 'vehicle_image'

    def __str__(self):
        return self.name

class main(models.Model):
    class Meta:
        db_table = 'main'

    def __str__(self):
        return self.name

    adID = models.CharField(max_length=11,primary_key=True)
    adType = models.CharField(max_length=10,null=True)
    condition = models.CharField(max_length=10,null=True)
    make = models.CharField(max_length=20,null=True)
    model = models.CharField(max_length=25,null=True)
    price = models.IntegerField(null=True)
    province = models.CharField(max_length=2,null=True)
    city = models.CharField(max_length=15,null=True)
    year = models.CharField(max_length=4,null=True)
    kilometers = models.CharField(max_length=13,null=True)
    exterior_color =  models.CharField(max_length=15,null=True)
    fuel_type = models.CharField(max_length=35,null=True)
    body_type = models.CharField(max_length=25,null=True)
    full_vehicle = models.CharField(max_length=100,null=True)
    #No need for FK a constraint
    #full_vehicle = models.ForeignKey(vehicle_image,on_delete=models.SET_NULL,null=True,db_column='full_vehicle')

class time(models.Model):
    class Meta:
        db_table = 'time'

    def __str__(self):
        return self.name

    adID = models.CharField(max_length=11,primary_key=True)
    time_entered = models.DateTimeField(null=True)
    time_updated = models.DateTimeField(null=True)

website/dashboards/forms.py
from django import forms
from .models import main, time


class CarForm(forms.Form):
    vehicle_type =  forms.ModelChoiceField(
        queryset = main.objects.values('body_type').distinct(),
    )
    make = forms.ModelChoiceField(
        queryset = main.objects.none()
    )
    model = forms.ModelChoiceField(
        queryset = main.objects.none()
    )
    year = forms.ModelChoiceField(
        queryset = main.objects.none()
    )

    class Meta:
        fields = ("vehicle_type", "make", "model", "year")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['make'].queryset = main.objects.none()

website/dashboards/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpRequest
from django.http import JsonResponse
from django.template import loader
from dashboards.models import main
from django.http import JsonResponse
from django.utils.safestring import SafeString
from django.db.models import Count, Q
# Create your views here.
#Documentation links:
#Queries: https://docs.djangoproject.com/en/dev/topics/db/aggregation/#filtering-on-annotations

def index(request):
    type_list = main.objects.values('body_type').filter(~Q(body_type = '-'))\
                .annotate(num_type=Count('body_type')).filter(num_type__gt=200).order_by('body_type')
    # type_list = main.objects.values('body_type').distinct().order_by('body_type')
    # print(type_list)
    context = {'types':type_list}
    return render(request,'dashboards/home_form.html',context)

def make_choices_ajax(request):
    choice = request.GET.get('id')
    makes_list = main.objects.filter(body_type=choice).values_list('make', flat=True)\
                .annotate(num_make=Count('make')).filter(num_make__gt=100).order_by('make')
    # makes_list = main.objects.filter(body_type=choice).values_list('make', flat=True).distinct().order_by('make')
    context = {'makes':makes_list}
    return render(request,'dashboards/make_dropdown.html',context)

def model_choices_ajax(request):
    choice = request.GET.get('id')
    choices = choice.split('/')
    # model_list = main.objects.filter(body_type=choices[0], make=choices[1]).values_list('model', flat=True).distinct().order_by('model')
    model_list = main.objects.filter(body_type=choices[0], make=choices[1]).values_list('model', flat=True)\
                .annotate(num_model=Count('model')).filter(num_model__gt=20).order_by('model')
    
    context = {'models':model_list}
    return render(request,'dashboards/model_dropdown.html',context)

def year_choices_ajax(request):
    print(request)
    choice = request.GET.get('id')
    choices = choice.split('/')
    year_list = main.objects.filter(body_type=choices[0], make=choices[1], model=choices[2]).values_list('year', flat=True)\
                .annotate(num_year=Count('year')).filter(num_year__gt=20).order_by('-year')
    
    context = {'years':year_list}
    return render(request,'dashboards/year_dropdown.html',context)

def validate_dashboard(request):
    #default json
    data ={
        'type': request.GET['type'],
        'make':request.GET['make'],
        'model':request.GET['model'],
        'year':request.GET['year'],
        'descriptive':request.GET['descriptive'],
        'value':request.GET['value'],
        'success':True,
        'error':None
    }
    #form handling
    if request.GET['type']=='':
        data['error']='type'
    elif request.GET['make']=='':
        data['error']='make'
    elif request.GET['model']=='':
        data['error']='model'
    elif request.GET['year']=='':
        data['error']='year'
    elif request.GET['descriptive'] == 'false' and request.GET['value'] == 'false':
        data['error']='Please select at least one dashboard'

    if data['error']!=None: data['success']=False

    return JsonResponse(data)

def dashboard_display(request,descriptive,value,type,make,model,year):
    # CONVERT to booleans
    descriptive = descriptive == "true"
    value = value == "true"

    if descriptive and not value:
        context = {'data':'{"vehicle_data":{"value":"'+type+'$'+make+'$'+model+'$'+year+'"}}',
                    'dropdown_link':request.path,
                    'dropdown_name':make+' '+model+' '+year,
                    'image_path':'vehicle_images/'+make+'_'+model+'_'+year+'.jpg'
                    }
        return render(request,'dashboards/descriptive_tmp.html',context)
    elif descriptive and value:
        context = {'data':'{"vehicle_data":{"value":"'+type+'$'+make+'$'+model+'$'+year+'"}}',
                    'dropdown_link':request.path,
                    'dropdown_name':make+' '+model+' '+year,
                    'image_path':'vehicle_images/'+make+'_'+model+'_'+year+'.jpg'
                    }
        return render(request,'dashboards/descriptive_value_tmp.html',context)

def update_link_cookies(request):
    # print(request)
    # print(request.GET.get('link', False))
    # print(request.GET.get('name_link', False))
    # print(request.method)

    if request.method=='GET':

        response = HttpResponse("SET COOKIE")
        #First check if cookie exists
        for i in range(1,7):
            try:
                if request.COOKIES['dashboard_link_'+ str(i)] == request.GET.get('link', False):
                    return HttpResponse()
            except KeyError:
                break
        #Check which links are available (max 6)
        for i in range(1,7):
            try:
                request.COOKIES['dashboard_link_'+ str(i)]
            except KeyError:
                response.set_cookie('dashboard_link_'+ str(i),request.GET.get('link', False))
                response.set_cookie('dashboard_name_'+ str(i),request.GET.get('name_link', False))

                return response
        #Overide the oldest saved dashboard (reorder)
        for i in range(1,7-1):
            response.set_cookie('dashboard_link_'+ str(i),request.COOKIES['dashboard_link_'+ str(i+1)])
            response.set_cookie('dashboard_name_'+ str(i),request.COOKIES['dashboard_name_'+ str(i+1)])

        response.set_cookie('dashboard_link_6',request.GET.get('link', False))
        response.set_cookie('dashboard_name_6',request.GET.get('name_link', False))

        return response

def clear_cookies(request):

    response = HttpResponse("REMOVE COOKIES")

    for i in range(1,7):
        try:
            response.delete_cookie('dashboard_link_'+ str(i))
            response.delete_cookie('dashboard_name_'+ str(i))
        except:
            break

    return response

website/dashboards/templates/dashboards/descriptive_tmp.html
{% extends "dashboards/base_generic.html" %}
{% load static %}
{% block content %}
<div class="dashboardHeader">
  <h1 class="dashboardText">Dashboard - Descriptive Analytics: {{ dropdown_name }}</h1>
  <img class="dashboardImage" src="{% static image_path %}" width="200" height="135">
</div>
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
<div>

<div class="dashboardContainer">
  <div class="row">
    <div class="col px-0">
        <!-- <div class="dashboardSidebar"> -->
          <button class="dashboardButton" type="button">Save Dashboard</button>
          <button type="button" class="dashboardButton" data-toggle="modal" data-target="#descriptiveModal"> 
            Statistical Terms
          </button>
        <!-- </div> -->
    </div>
    <div class="col-10 px-0">
        <!-- <div class="mainDashboard"> -->
          {% load plotly_dash %}
          {% plotly_app name="descriptive" ratio=1.4 initial_arguments=data %}
        <!-- </div> -->
    </div>
  </div>
</div>

<div class="modal fade" id="descriptiveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Statistical Terms</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span class="modalHeaders">Descriptive Statistics</span>
        <hr>
        <span class="modalSubHeaders">Mean:</span> Average of the sample data.
        <br>
        <span class="modalSubHeaders">Median:</span> The middle value seperating the lower and upper half of the sample data.
        <br>
        <span class="modalSubHeaders">Variance:</span> Measures how far a set of numbers are spread out from the average(mean) value.
        <br>
        <span class="modalSubHeaders">SD (Standard Devation):</span> The square root of the variance. Measures the spread but in the same units (price) as the sample data. For example, 68% of the sample vehicles fall in the price range [mean - 1*SD, mean + 1*SD] or one standard deviation.
        <br>
        <span class="modalSubHeaders">Min/Max:</span> The minimum and maximum values in the sample data.
        <br>
        <hr>
        <span class="modalHeaders">Posting Details</span>
        <hr>
        <span class="modalSubHeaders">Mean Volume:</span> The average number of open postings (vehicles) over the entire period data is collected. Represents activity/popularity of a vehicle. 
        <br>
        <span class="modalSubHeaders">Mean Turnover (days):</span> The average length of time in days a posting is open. Represents the amount of time it takes to sell a vehicle.
        <br>
        <span class="modalSubHeaders">Dealer(%):</span> The precentage of postings that are by a vehicle dealership (as opposed to a private listing)
        <hr>
      </div>
    </div>
  </div>
</div>

<script>
  //TODO: if image not available load alt image
  //https://stackoverflow.com/questions/1451138/how-can-i-get-the-domain-name-of-my-site-within-a-django-template
  // $.ajax({url:"//{{ request.get_host }}/static/vehicle_images/Pontiac_Montana SV6_2008.jpg",type:'HEAD',
  //   error:function(){alert("hello")}});
  
  $('.dashboardButton').click(function(){
    var link = "{{dropdown_link}}";
    var title = "{{dropdown_name}}";
    var urlAddLinks = "{% url 'dashboards:update_link_cookies' %}";

    var dashboardColor = $('#highlightText').css("color");
    $('#highlightText').css("color","#f70027");
    $('#highlightText').animate({color: dashboardColor}, 3000);

    $.ajax({
      url: urlAddLinks,
      data: {
        'link': link,
        'name_link': title,
      },
      dataType: 'json',
    });
    
    var inDropdown = $( ".dropdown-menu" ).text().match(title)
    if (inDropdown == null){
      $('.dropdown-menu').prepend('<a class="dropdown-item"></a>');
      $(function() {
        $('.dropdown-item').first().attr('href',link);
        $('.dropdown-item').first().text(title);
      });
    }
  });

  $('#clear-dashboards').click(function(){
    console.log("Hello")
    var urlClearCookies = "{% url 'dashboards:clear_cookies' %}";

    $.ajax({
      url: urlClearCookies,
    });
    // var save = $('#clear-dashboards').detach();
    $(".dropdown-item").remove()

  });

  getCookies();

</script>
{% endblock %}

website/dashboards/templates/dashboards/descriptive_value_tmp.html
{% extends "dashboards/base_generic.html" %}
{% load static %}
{% block content %}
<div class="dashboardHeader">
  <h1 class="dashboardText">Dashboard: {{ dropdown_name }}</h1>
  <img class="dashboardImage" src="{% static image_path %}" width="200" height="135">
</div>
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
<div>

<div class="dashboardContainer">
  <div class="row">
    <div class="col px-0">
        <!-- <div class="dashboardSidebar"> -->
          <button class="dashboardButton" id="dashboardButtonTabs" type="button">Save Dashboard</button>
          <button type="button" class="dashboardButton" data-toggle="modal" data-target="#descriptiveModal"> 
            Descriptive Terms
          </button>
          <button type="button" class="dashboardButton" data-toggle="modal" data-target="#descriptiveValueModal"> 
            Value Terms
          </button>
        <!-- </div> -->
    </div>
    <div class="col-10 px-0">
        <!-- <div class="mainDashboard"> -->
        {% load plotly_dash %}
        {% plotly_app name="descriptive_value" ratio=1.5 initial_arguments=data %}
        <!-- </div> -->
    </div>
  </div>
</div>
<!-- Descriptive Modal -->
<div class="modal fade" id="descriptiveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Statistical Terms</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span class="modalHeaders">Descriptive Statistics</span>
        <hr>
        <span class="modalSubHeaders">Mean:</span> Average of the sample data.
        <br>
        <span class="modalSubHeaders">Median:</span> The middle value seperating the lower and upper half of the sample data.
        <br>
        <span class="modalSubHeaders">Variance:</span> Measures how far a set of numbers are spread out from the average(mean) value.
        <br>
        <span class="modalSubHeaders">SD (Standard Devation):</span> The square root of the variance. Measures the spread but in the same units (price) as the sample data. For example, 68% of the sample vehicles fall in the price range [mean - 1*SD, mean + 1*SD] or one standard deviation.
        <br>
        <span class="modalSubHeaders">Min/Max:</span> The minimum and maximum values in the sample data.
        <br>
        <hr>
        <span class="modalHeaders">Posting Details</span>
        <hr>
        <span class="modalSubHeaders">Mean Volume:</span> The average number of open postings (vehicles) over the entire period data is collected. Represents activity/popularity of a vehicle. 
        <br>
        <span class="modalSubHeaders">Mean Turnover (days):</span> The average length of time in days a posting is open. Represents the amount of time it takes to sell a vehicle.
        <br>
        <span class="modalSubHeaders">Dealer(%):</span> The precentage of postings that are by a vehicle dealership (as opposed to a private listing)
        <hr>
      </div>
    </div>
  </div>
</div>
<!-- Value Modal -->
<div class="modal fade" id="descriptiveValueModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Statistical Terms</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        ...

      </div>
    </div>
  </div>
</div>
<script>
  $('.dashboardButton').click(function(){
    var link = "{{dropdown_link}}";
    var title = "{{dropdown_name}}";
    var urlAddLinks = "{% url 'dashboards:update_link_cookies' %}";

    var dashboardColor = $('#highlightText').css("color");
    $('#highlightText').css("color","#f70027");
    $('#highlightText').animate({color: dashboardColor}, 3000);

    $.ajax({
      url: urlAddLinks,
      data: {
        'link': link,
        'name_link': title,
      },
      dataType: 'json',
    });
    
    var inDropdown = $( ".dropdown-menu" ).text().match(title)
    if (inDropdown == null){
      $('.dropdown-menu').prepend('<a class="dropdown-item"></a>');
      $(function() {
        $('.dropdown-item').first().attr('href',link);
        $('.dropdown-item').first().text(title);
      });
    }
  });

  $('#clear-dashboards').click(function(){
    console.log("Hello")
    var urlClearCookies = "{% url 'dashboards:clear_cookies' %}";

    $.ajax({
      url: urlClearCookies,
    });
    $(".dropdown-item").remove()

  });

  getCookies();

</script>
{% endblock %}

website/dashboards/templates/dashboards/hello.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    hello
  </body>
</html>

website/dashboards/templates/dashboards/home_form.html
{% extends "dashboards/base_generic.html" %}

{% block content %}
<div class="container">
<div class="jumbotron bg-light text-dark">
  <h1>Vehicle</h1>
  <hr>
    <form id="mainForm" method="GET"
    data-urlmakes="{% url 'dashboards:make_choices_ajax' %}"
    data-urlmodels="{% url 'dashboards:model_choices_ajax' %}"
    data-urlyears="{% url 'dashboards:year_choices_ajax' %}"
    >

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"><span class="labels">Vehicle Type</span></label>
      <div class="col-sm-10">
        <select class="custom-select col-8" id="dropType" name="TypeDropdown">
        <option>---------</option>
        {% for item in types %}
        <option value="{{ item.body_type }}">{{ item.body_type }}</option>
        {% endfor %}
      </select>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="dropMake"><span class="labels">Make</span></label>
      <div class="col-sm-10">
        <select class="custom-select col-8" id="dropMake" name="MakeDropdown">
          <option value="">---------</option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="dropModel"><span class="labels">Model</span></label>
      <div class="col-sm-10">
        <select class="custom-select col-8" id="dropModel">
          <option value="">---------</option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="dropYear"><span class="labels">Year</span></label>
      <div class="col-sm-10">
        <select class="custom-select col-8" id="dropYear">
          <option value="">---------</option>
        </select>
      </div>
    </div>
    </form>
    <h1>Dashboards</h1>
    <hr>
      <div id="toggle-wrapper">
        <div class="checkbox">
          <label>
            <input id="descriptiveCheck" type="checkbox" data-toggle="toggle">
            <span class="toggle-labels">Descriptive Analytics</span>
          </label>
        </div>
        <div class="checkbox">
          <label>
            <input id="valueCheck" type="checkbox" data-toggle="toggle">
            <span class="toggle-labels">Value Analytics</span>
          </label>
        </div>
        <div class="checkbox disabled">
          <label>
            <input id="predictiveCheck" type="checkbox" disabled data-toggle="toggle">
            <span class="toggle-labels">Predictive Analytics</span>
          </label>
        </div>
        </div>

    <hr>

    <form id="btnId"  method="GET" data-urlsubmit="{% url 'dashboards:validate_dashboard' %}">
      <div id="button-wrapper">
        <button class="btn btn btn-primary btn-lg btn-block" type='button'>
          Generate Dashboard
        </button>
          <!-- <a class="btn btn btn-primary btn-lg btn-block" href="#" type="submit" role="button">Generate Dashboard</a> -->
      </div>
      <div class="submitErrors">
        <div id="error"></div>
      </div>
    </form>
</div>
</div>

  <script >
    $("#dropType").change(function() {
      var urlMakes = $('#mainForm').data('urlmakes');
      var idMakes = $(this).val();
      // console.log(idMakes)
      $.ajax({
        url: urlMakes,
        data: {
          id: idMakes
        },
        success: function(response) {
          $('#dropMake').html(response)
        }
      })
    });

    $("#dropMake").change(function() {
      var urlModels = $('#mainForm').data('urlmodels');
      var prevIdType = $('#dropType').val();
      var prevIdMake = $('#dropMake').val();
      var idModels = $(this).val();
      //console.log(idMakes)
      $.ajax({
        url: urlModels,
        data: {
          id: prevIdType+'/'+prevIdMake
        },
        success: function(response) {
          $('#dropModel').html(response)
        }
      })
    });

    $("#dropModel").change(function() {
      var urlYears = $('#mainForm').data('urlyears');
      var prevIdType = $('#dropType').val();
      var prevIdMake = $('#dropMake').val();
      var prevIdModel = $('#dropModel').val();
      var idYears = $(this).val();
      //console.log(idMakes)
      $.ajax({
        url: urlYears,
        data: {
          id: prevIdType+'/'+prevIdMake+'/'+prevIdModel
        },
        success: function(response) {
          $('#dropYear').html(response)
        }
      })
    });

    $("#btnId").click(function() {
      var TypeVal = $("#dropType").val();
      var MakeVal = $("#dropMake").val();
      var ModelVal = $("#dropModel").val();
      var YearVal = $("#dropYear").val();
      var DescriptiveVal = $("#descriptiveCheck").prop("checked");
      var ValueVal = $("#valueCheck").prop("checked");
      var urlSubmit = $("#btnId").data('urlsubmit');

      $.ajax({
        url: urlSubmit,
        data: {
          'type': TypeVal,
          'make': MakeVal,
          'model': ModelVal,
          'year': YearVal,
          'descriptive': DescriptiveVal,
          'value': ValueVal,
        },
        dataType: 'json',
        success: function(response) {
          if(response.success){
            $("#btnId").attr("action", "dashboard/descriptive="+response.descriptive+"/value="+response.value+"/"+response.type+"/"+response.make+"/"+response.model+"/"+response.year+"/");
            $("#btnId").submit();
          }else{
            if($('#error').children().length>0){ $('#error p' ).remove(); }
            if(response.error !== 'Please select at least one dashboard'){
              $("#error").append("<p>Please fill in "+response.error+"</p>")
            }else{
              $("#error").append("<p>"+response.error+"</p>")
            }
          }
        }
      })
    });

  getCookies();
  </script>
{% endblock %}

website/dashboards/templates/dashboards/make_dropdown.html
<option value="">---------</option>
{% for item in makes %}
<option value="{{ item }}">{{ item }}</option>
{% endfor %}

website/dashboards/templates/dashboards/model_dropdown.html
<option value="">---------</option>
{% for item in models %}
<option value="{{ item }}">{{ item }}</option>
{% endfor %}

website/dashboards/templates/dashboards/year_dropdown.html
<option value="">---------</option>
{% for item in years %}
<option value="{{ item }}">{{ item }}</option>
{% endfor %}